### ISSUE TITLE
A way to add a CAT file

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#102]
**Is your feature request related to a problem? Please describe.**
ref.py relies on the presence of a CAT file, which is never loaded into the resulting hdul, and I have to rename the XRT file to the CAT file. Though this is a fix that works, I would think that being able to find reference stars for background stars would be more appropriate, as currently with only the XRT file (renamed to CAT in my case) we only find variable stars.

**Describe the solution you'd like**
I would like the resulting hdul file, after it has been run through the pipeline to have:

1. CAT
2. REF
3. XRT
4. SCI

Currently I am able to get three of the four, excluding CAT.
The CAT file should be equivalent to running the raw image through extract, such that the file would contain information about **all** stars, not just variable stars.
If the CAT file is already present, there should be a mechanism to skip this.
**Describe alternatives you've considered**
The following command:
sdi read -d GTAnd_SCI/ align extract -w CAT 1 subtract extract write -d sdiPTF_output/

does not work, and I'm not sure why.
**Additional context**
The PTF files do not come with an inbuilt CAT file, only a PRIMARY header. This is why I need a way to add this feature in.

**Comment by varun-magesh** [comment]
The extract command was intended for this use, the command you described should work. What is the state of the hduls after the first extract in your suggested command?

**Comment by PK0207** [comment]
Command: sdi read -d GTAnd_SCI/ align extract -w CAT 1 write -d sdiPTF_output/
When I do the first extract, I get a CAT file with 302 sources in it. 

sdi read -d GTAnd_SCI/ extract -w CAT 1 write -d sdiPTF_output/
After doing this, I get 247 sources (without align)

If I run the command above, what I get is just the SCI and the XRT extensions

**Comment by PK0207** [comment]
**NOTES FROM 7/21 meeting:**
To get both desired tables, the write option should be present in both?
In the version that Edgar has he can produce XRT and CAT at the same time and he doesn't run subtract.

Subtract seems to overwrite all of the overwrites all of the data

But my issue is that I can't have both at the same time because I run subtract

Output of command is PRIMARY - refers to residual image
sdi read -d small_set/ align extract -w CAT 1 write -d sditest_ref/ _works to write the CAT file, keeps the SCI file_
sdi read -d sditest_ref/ align subtract extract write -d sditest_output/  _Overwrites all of the previous headers and only keeps XRT and PRIMARY_

INPUT OF SUBTRACT - image["PRIMARY"].data - pixel values in the raw image
OUTPUT OF SUBTRACT (algorithm) - residual in the same format (pixel values in an image)

OUTPUT OF SUBTRACT (fits file) - PRIMARY named hdu - seems to overwrite all of the existing hdul

[All of the hdu from the original result of the first extract]

Seems to be related to the FIXME 36

**Comment by EdgarMao** [comment]
Some testings on my end revealed some different issues:

While I am able to run `extract` multiple consecutive times without problem like PK described, I receive an error (ValueError: array must be 2-d) when trying to run `subtract` before `extract`. This problem is most likely due to the strange output of subtract when I run sdi on my end:

If I run something along the lines of `sdi read align subtract write -d sdi_output/`, I will recieve an output of many fits files with the PRIMARY hdu and only one dimension. It seems like `subtract` is unable to group its output into a 2-d table, which then causes errors with the subsequent `extract`. 

**However**, for some yet to be discovered reason, this issue did not appear when PK ran sdi. Nevertheless, both my issue and PK's issue seem to point toward the same FIXME in `subtract` (FIXME on line 36), which is the part where `subtract` formats its output.

P.S. The raw data I was using for my tests have doc names in the following format: tfn0m414-kb99-20180831-0290-e91.fits.fz , I'm fairly certain that PK and I are using the same version of the pipeline, which may suggest the raw data we are using is different.
