### ISSUE TITLE
Pipeline doesn't run with PTF images in a virtual environment

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#104]
**Describe the bug**
When running PTF images through the version of the pipeline that is on the `master` branch, while in a virtual environment (venv), the following error shows up:
`ValueError: Big-endian buffer not supported on little-endian compiler`

This error arises in `align.py`, and `subtract.py` when working in the virtual environment.

The issue **does not** arise when working with the images outside the virtual environment.

**Also:** The pipeline runs with no issues on LCO images outside the venv, have not tested its behaviour in the following ways:

1. Within the venv on the `master` version of the pipeline
2. Within the venv in the version of the pipeline on the `norm_sources` branch

**To Reproduce**
1. Go into the pipeline virtual environment
2. Run the following command: `sdi read -d /home/pkotta/GTAnd_SCI/ align subtract extract write -d /home/pkotta/sdiPTF_output/`
3. See error
4. You may have to copy these images into your home directory to see it work

**Expected behavior**
The expectation is for the images to run through each of the above commands with no issues.

**Desktop (please complete the following information):**
- Git pulled: The same day
**Additional context**
On the `norm_sources` branch, in order to fix this issue I have changed various lines as follows: <br>
`.data` --> `.data.byteswap().newbyteorder()`
<br>
Images to test this on are in /home/bfogiel/LCO_images and /home/bfogiel/PTF_images
<br>
This may just be a very special use case, but I wanted to check just in case. If it is a very special use case, I believe it should be ok for me to work in the norm_sources branch instead of master for now.

**Comment by benfogiel** [comment]
Fixed align.py. Looks like the LCO and PTF images were storing themselves differently in memory either as little or big endian. The venv compiler can only compile little endian, hence, the error. 

Solution:
PK had the right idea with swapping the order bytes are stored with `.data.byteswap().newbyteorder()` because little endian stores bytes in the reverse order as big endian does. However, this method cannot be executed for both LCO and PTF images, so just checked if the the output array can be initialized and if not, the byte order is swapped. (lines 45-50)

Tested both venv and local and everything runs without error. Pushed revised code to norm_sources branch.
