### ISSUE TITLE
Flux not loaded into resulting CAT table (Simulated images)

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#109]
flux not loaded into resulting CAT table after everything is run through the pipeline, will run again to see if this is a recurring issue.
EDIT: Happened again on the second run. This does not happen to normal files run through, and has not happened before so I don't know what's going on.

_Originally posted by @PK0207 in https://github.com/ucsbdeepspace/sdi_pipeline/issues/87#issuecomment-878688910_

**Comment by PK0207** [comment]
Files for testing are in /home/bfogiel/issue_87. This includes 10 simulated images, and the original csv file for the variable star

**Reading the .csv file**

row = np.genfromtxt('lc_GTAnd.csv',delimiter='\t')
time = []
magauto = []
magerr = []
for row in data:
    time.append(row[0])
    magauto.append(row[1])
    magerr.append(row[2])`

**The resulting data**
The resulting images should have the the PRIMARY hdu and the BINTable hdu (Should be named CAT).
The CAT table is the result from extract.py . It is called the catalog file, and it contains lists of data, where each list item corresponds to one object from the original image.
**The issue**
Currently, the table is either missing data entirely, or missing flux specifically. The command run is as above. Issue is most likely with extract, or the way the images are created. (i.e., extract doesn't have enough information in the headers to find flux)

**A new branch should be made for testing**

**Comment by PK0207** [comment]
Retry yesterday came back with empty tables for some reason. So issue still stands.

**Comment by benfogiel** [comment]
I'm thinking that this is due to the fact that the variable star within the fits images in dir bfogiel/issue_87 varies closely around the mean of these images which causes subtract to output mostly blank fits images. When this star deviates enough away from the mean, subtract will output a non blank image of which the flux can be obtained (with the sample in bfogiel/issue_87, 2 images are not blank, they do show up in different orders though after each run, but I don't think this is an issue b/c they have the same flux mag every time). Another thing to consider is that I don't think the flux magnitudes can be compared to the csv file because subtract uses combine for it's template image of which takes the mean of each pixel in the hdul then subtract subtracts each pixel of every hdu from this mean (essentially truncating each value). Therefore, if I am not mistaken, the flux magnitude should be less, however, in terms of deviations from the mean (amplitude) and the period of the light curve, this should be congruent with the csv. Haven't checked this yet

**Comment by benfogiel** [comment]
Running extract with the default threshold value of 3.0, 18% of the bfogiel/issue_87/image_fits3 have fluxes. Lowering to a threshold value of 2.0, over 30% of the same set of images have fluxes

**Comment by benfogiel** [comment]
investigating further, extracting the flux from bfogiel/issue_87/fits_images did not yield as good results as previously thought. Realized that I was including fluxes from sources that were of no interest. Getting the fluxes of the correct source: Threshold = 3, 16.8% had fluxes; Threshold = 1.5, 30% had fluxes.

**Comment by benfogiel** [comment]
Now, using another set of images from /home/cole/sim_code/lightcurve_stuff/reg_RR/image_fits/ and extracting the flux we get a lot better results. Threshold = 3, 40% had fluxes, Threshold = 1.5, 43% had fluxes

**Comment by benfogiel** [comment]
ran Cole's images with adaptive bramich and results did not differ much. threshold = 3: 41.67% threshold, threshold = 1.5: 45%

**Comment by benfogiel** [comment]
Source: /home/cole/sim_code/lightcurve_stuff/reg_RR/image_fits/
Residuals (adaptive bramich): /home/bfogiel/output_t_3 AND /home/bfogiel/output_t_1.5
Note: ‘t_3’ and ‘t_1.5’ refers to the respective extraction thresholds

**Comment by PK0207** [comment]
Not using simulated images anymore
