### ISSUE TITLE
Image data becoming misaligned from WCS after align.

### ISSUE THREAD

**Issue by JasperWebb** [deepspace-ucsb/sdi_pipeline#132]
### Issue
In the `align` script the image data is transformed to match a single image. The image that everything is matched to is the last image in hduls_list.   I don't believe that the **WCS coordinates** which are tied to the image data are updated to reflect the transformations carried out in `align`. 
This could affect RA/DEC and other position dependent (catalog matching, etc..) things down stream. 

### Possible solutions
Im not very familiar with **WCS** so I don't know how possible it would be to calculate a correction to WCS to fix the alignment. If you know anything about it please let me know. 

An idea to fix this would be to transfer the **WSC** from the single image used to match to all files matched to it.
However, I'm not sure is **WCS** is time /location dependant. If you were to try and align many images taken over many nights from difference sources this could cause WCS to be even less accurate.

**Comment by JasperWebb** [comment]
Maybe it would be possible to correct the WCS individually? 
https://python4astronomers.github.io/astropy/wcs.html

**Comment by JasperWebb** [comment]
LCO team calculate RA and dec from WCS information here. 

https://github.com/LCOGT/banzai/blob/master/banzai/astrometry.py

**Comment by PK0207** [comment]
Goal: Keep track of which star is which as it goes through the pipeline Though align, subtract, and data from XRT don't need RA DEC data to run the function `sep.extract` , we need RA and DEC information for each star to be preserved so that any transformation won't result in misidentification of stars based on xy position.

Currently: LCO [CAT] has ra dec from BANZAI, PTF and likely other sources of images don't come with a source catalog.

Where there is no CAT, we want to produce a CAT and include ra dec information in it. This means this process should be done before align so that it is independent of the transformation.

If we don't have a CAT file, what we do is write RA DEC to a CAT file we create using WCS.

Astroalign is best suited for observations taken over a single night. For observations taken further apart, say years, this would not be as accurate. (We should have multiple align algorithm options?).

Make sure that all reference frames are J2000 (January 1st 12:00AM 2000) <- how?

The reference fits file used for aligning (found by best SNR) [CAT] can be used as the basis for every file because of the linear transformation.

Keep the reference image somewhere (outside of the pipeline output hduls), without processing it. (Can be temporarily stored)

CHECKS:
 Check that each RA DEC is the same across CATs (it should be). If not, then time is not being accounted for.

Second check: transform xy of XRT to ra dec (using WCS) and see if we find matches in the reference CAT hdu.

That would confirm that the header (WCS) for the reference image can be used for all of the images.

If it passes these checks, we can proceed with the original plan to have the cards that SEP uses to calculate WCS all be the same across all of the headers in ALIGN.


STEPS (before checks):
Write reference header to ALGN. Original header is in original files. If header in ALGN is the reference header, then it will be the same in SUB (double check this), so extract can run just the same.

Add ra dec transforms to extract function

**Comment by EdgarMao** [comment]
Quick question about our choice of reference frame: 

What is the advantage of J2000? Are we choosing this because most of our current images are taken using this coordinate system?

**Comment by PK0207** [comment]
> Quick question about our choice of reference frame:
> 
> What is the advantage of J2000? Are we choosing this because most of our current images are taken using this coordinate system?

My personal reasoning is that it's a popular system that doesn't change, so our pipeline will remain standardized for longer.

**Comment by JasperWebb** [comment]
https://fits.gsfc.nasa.gov/fits_wcs.html

**Comment by PK0207** [comment]
- Added ra dec information in output catalog information (extract), and hdul naming is also working
- ra and dec calculated in ICRS
- Fluctuations rarely exceed 1 arcsecond, which is the error we expect due to WCS fluctuations.
- Checked that RA DEC are correct by searching for the star in the SIMBAD database and comparing to our image visually (shown below), so that RA and DEC are accurate
![image](https://user-images.githubusercontent.com/30590837/146461637-c63e145d-d146-4ab4-9965-48d6d7dd27f4.png)

**Comment by PK0207** [comment]
Resolved
