### ISSUE TITLE
Implement Alard-Lupton in memory through OIS

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#4]
**M** [OIS](https://github.com/toros-astro/ois)

**Comment by varun-magesh** [comment]
We want to implement OIS as a replacement for hotpants because it allows us to try a few different DIA algorithms including Bramich and Adaptive Bramich while maintaining hotpant’s Alard-Lupton. It also operates entirely in-memory so it’ll get rid of tmpdir nastiness. Current subtraction is done in [`subtract.subtract`](https://github.com/ucsbdeepspace/sdi_pipeline/blob/133e72d786704c1dadadd1c9682696a7d7a3f511/subtract/subtract.py#L16)
