### ISSUE TITLE
Plot false positives in figure 16

### ISSUE THREAD

**Issue by nlynn** [deepspace-ucsb/sdi_pipeline#47]

**Comment by varun-magesh** [comment]
This is Cole

**Comment by coleslenkovich** [comment]
Varun and I discussed over Slack a while ago, however I think we should focus on the F1 statistic in the paper. (I briefly describe why in write-up). As far as a plot for F1 goes, it does not make since to graph against magnitude since it depends greatly on the detection % and the graph ends up looking exactly like our magnitude detection plot.
