### ISSUE TITLE
`extract` should include ra & dec information

### ISSUE THREAD

**Issue by varun-magesh** [deepspace-ucsb/sdi_pipeline#73]
Currently, `extract` gives back what `sep` gives us. This is pretty complete data, but does not have `ra` and `dec` columns which are pretty important. We should get `ra` and `dec` using the WCS header and x-y coords and add these columns to the `XRT` table.

**Comment by PK0207** [comment]
**TESTING in WCS_alignment branch**

Added RA/DEC information using pixel_to_skycoord, wrote out using:
`cat = fits.BinTableHDU(data=sources, header=header,
                                     name=extname, ver=extver)
        out_cols = cat.data.columns
        new_cols = fits.ColDefs([fits.column(name = 'ra',format = 'D',array=ra),fits.column(name = 'dec', format = 'D', array=dec)])
        new_table = fits.BinTableHDU().from_columns(out_cols + new_cols)
        hdul.append(fits.BinTableHDU(data=new_table, header = header, name = extname, ver=extver))`

testing using: `sdi read -d small_set/ align subtract extract write -d sditest_output/`

result: 
`new_cols = fits.ColDefs([fits.column(name = 'ra',format = 'D',array=ra),fits.column(name = 'dec', format = 'D', array=dec)])
TypeError: 'module' object is not callable`

FIX: Had to capitalize fits.Column, after which table was created successfully.

Re-testing using same commands

Results: `TypeError: Table data has incorrect type.`
from `hdul.append(fits.BinTableHDU(data=new_table, header = header, name = extname, ver=extver))`

FIX: new_table is a fitsBinTable itself, not just a data table. This is the new hdu to append.
`new_table = fits.BinTableHDU(header = header, name = extname, ver=extver).from_columns(out_cols + new_cols)`

re-testing using same commands:
results:
Ran successfully but the extension name is not loaded in. RA and DEC values look reasonable.

**Moving on to test 2, running on SCI instead of SUB.**

testing using: `sdi read -d small_set/ extract --read_ext SCI -w CAT 1 write -d sditest_output/`
results: Runs successfully, but still no extension name. Committing and pushing for now.

**Comment by PK0207** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/30590837/149845636-ee435a54-5665-4e39-bbd3-2e067132ec9e.png)
![image](https://user-images.githubusercontent.com/30590837/149845645-aee95dbc-824f-422d-9c22-f75c1f118df3.png)
